Source : 파이썬 머신러닝 완벽 가이드(권철민, 위키북스)

# Numpy  
> **Numpy**  
Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지이다.   

- Numpy를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요하다.   
1. 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있고, 이들 알고리즘의 입력 및 출력 데이터를 넘파이 배열 타입으로 사용하기 때문
2. 넘파이가 배열을 다루는 기본 방식을 이해하면 판다스 등 다른 데이터 핸들링 패키지를 이해하는 데에도 많은 도움이 됨

## 6. 행렬의 정렬 : sort(), argsort()  


### 6-1. 행렬 정렬  
- **np.sort()**  
: 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환  
default는 행렬 내 원소를 오름차순으로 정렬, 내림차순으로 정렬하려면 `[::-1]`을 적용

- **ndarray.sort()**  
: 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None  
default는 행렬 내 원소를 오름차순으로 정렬, 내림차순으로 정렬하려면 `[::-1]`을 적용

#### 다차원 행렬의 정렬  
axis 축 값 설정을 통해 row 방향, 혹은 column 방향으로 정렬을 수행  
(예시) 2차원 행렬 A  
- np.sort(A, axis=0) : 로우 방향으로 정렬  
- np.sort(A, axis=1) : 컬럼 방향으로 정렬

In [1]:
import numpy as np

# 정렬되지 않은 원본 행렬 생성
array_org = np.array([3, 1, 9, 5])
print('원본 행렬: ', array_org)

# np.sort()로 정렬
sort_array1 = np.sort(array_org)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', array_org)

# ndarray.sort()로 정렬
sort_array2 = array_org.sort()
print('ndarray.sort() 호출 후 반환된 정렬 행렬: ', sort_array2)
print('ndarray.sort() 호출 후 원본 행렬: ', array_org)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
ndarray.sort() 호출 후 반환된 정렬 행렬:  None
ndarray.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [2]:
# 내림차순으로 정렬
sort_array1_desc = np.sort(array_org)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


In [3]:
# 2차원 행렬 생성
array2d = np.array([[8, 12],
                    [7, 1]])
print('2차원 원본 행렬:\n', array2d)

# axis 0 (로우 방향) 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('axis 0 방향으로 정렬:\n', sort_array2d_axis0)

# axis1 (칼럼 방향) 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('axis 1 방향으로 정렬:\n', sort_array2d_axis1)

2차원 원본 행렬:
 [[ 8 12]
 [ 7  1]]
axis 0 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
axis 1 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 6-2. 정렬된 행렬의 인덱스를 반환하기  

- **np.argsort()**  
: 원본 행렬이 정렬되었을 때 기존 원본 행렬 인덱스를 ndarray 형으로 반환  
default는 행렬 내 원소를 오름차순으로 정렬, 내림차순으로 정렬하려면 [::-1]을 적용  

*ndarray에서 argsort()의 활용도가 매우 높다.*  
넘파이의 ndarray는 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없으므로, 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 한다.  
예를 들어, 학생별 시험 성적을 데이터로 표현하기 위해서는 학생의 이름과 시험 성적을 name_array, score_array와 같이 각각의 ndarray로 가져야 한다.  
이때 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 변환된 인덱스를 name_array[]에 넣어 팬시 인덱싱으로 추출할 수 있다.

In [4]:
# 정렬된 행렬의 원본 인덱스 반환
array_org = np.array([3, 1, 9, 5])
sort_indices = np.argsort(array_org)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [5]:
# 내림차순 정렬 후 원본 인덱스 반환
array_org = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(array_org)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [6]:
# 학생 별 시험 성적
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# 성적순으로 학생 이름을 출력하기
sort_indices_desc = np.argsort(score_array)[::-1]
print('성적 내림차순 정렬 시 score_array의 인덱스: ', sort_indices_desc)
print('성적 내림차순으로 name_array의 이름 출력: ', name_array[sort_indices_desc])

성적 내림차순 정렬 시 score_array의 인덱스:  [3 1 4 2 0]
성적 내림차순으로 name_array의 이름 출력:  ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


## 7. 선형대수 연산 : 행렬 내적과 전치 행렬 구하기

### 7-1. 행렬 내적(행렬 곱)  
- **np.dot()** : 두 행렬의 내적 구하기  

두 행렬 A와 B의 내적은 왼쪽 행렬의 로우(행)와 오른쪽 행렬의 칼럼(열)의 원소들은 순차적으로 곱한 뒤 그 결과를 모두 더한 값  
따라서 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산이 가능함

In [7]:
# 행렬 내적 구하기
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10], 
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 7-2. 전치 행렬  
원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 한다.  
예를 들어 2*2의 행렬 A가 있을 경우, A행렬의 1행2열의 원소를 2행1열의 원소로, 2행1열의 원소를 1행2열의 원소로 교환하는 것이다.  
이때 행렬 A의 전치 행렬은 A^T와 같이 표기한다.  

- **np.transport()** : 전치 행렬 구하기

In [8]:
# 전치 행렬 구하기
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])
transpose_mat2 = np.transpose(B)
print('B의 전치 행렬:\n', transpose_mat2)

A의 전치 행렬:
 [[1 3]
 [2 4]]
B의 전치 행렬:
 [[1 3 5]
 [2 4 6]]
